

services:
  netascore:
    image: netascore
    build: .
    #image: plusmobilitylab/netascore:local  # Name the locally built image
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
    - ./data:/usr/src/netascore/data
    command: "examples/settings_osm_query.yml"
    depends_on:
      netascore-db:
        condition: service_healthy

  netascore-db:
    image: postgis/postgis:13-3.2
    ports:
    - "5433:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 20s
      retries: 120

  pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=your_email@example.com
        - PGADMIN_DEFAULT_PASSWORD=your_password
      ports:
        - "8080:80"
      depends_on:
        netascore-db:
          condition: service_healthy